POST http://localhost:8000/api/v1/url-shortener
Content-Type: application/json

{
  "original_url": "https://www.example.com/some/long/path"
}

GET http://localhost:8000/api/v1/url-shorteners

GET http://localhost:8000/vcrizc