replicaCount: 1

image:
  repository: 192.168.1.200:30002/ivansanmartin/url-shortener
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "url-shortener"
fullnameOverride: "url-shortener"

namespace: ivansanmartin

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

secretRef:
  - secretRef:
      name: url-shortener-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/use-regex: "true"
  host: ivsm.link
  path: /
  pathType: ImplementationSpecific

securityContext:
  runAsUser: 0

labels:
  app: url-shortener